version: "3.9"

services:
  logger:
    build: .
    container_name: logger

    command: ./target/release/logger

    volumes:
      - ./logs:/app/logs:Z

  server:
    build: .
    container_name: server

    command: ./target/release/server

    depends_on:
      - logger

    ports:
      - "8080:8080"
